### ISSUE TITLE
Updating driver

### ISSUE THREAD

**Issue by XRaiderXD** [Syniurge/ShieldControllerWinDriver#4]
I have done it once before, But I had to reset my computer so now I have to do it again.
I followed the steps correctly but at the last step the driver doesn't show up, But If I uncheck compatible it shows up at Nvidia and I install it but it doesn't work.
What can I do?

Thanks in advance 
XRaiderXD.

![screenshot_1](https://cloud.githubusercontent.com/assets/24892481/21606332/f711942c-d1ae-11e6-8c38-ac582fe58273.png)
![screenshot_2](https://cloud.githubusercontent.com/assets/24892481/21606333/f714d2fe-d1ae-11e6-80bd-d77f962ca6c3.png)

**Comment by XRaiderXD** [comment]
![screenshot_3](https://cloud.githubusercontent.com/assets/24892481/21606401/88301366-d1af-11e6-8ffd-8cc52de94374.png)

Forgot to add this image.

**Comment by denostr** [comment]
Same problem, did you find the solution?

**Comment by XRaiderXD** [comment]
No I didn't

**Comment by Syniurge** [comment]
Hi and sorry for the very late reply, I've neglected my side projects for 3 months..

It seems that you didn't select the right device, instead of the "root" you selected one of the subdevices. That's why it's important to choose "Device by connection" in the Display menu of the device manager, then it's easier to find the right device, which should be named **"USB input device"** and should have 4 subdevices. The nVidia Shield controller driver should appear in the list for that one.

![devmgrbyconnection2](https://cloud.githubusercontent.com/assets/4272771/25073237/b9907be2-22e2-11e7-80a5-1269d6b79377.png)

And yes the installation instructions aren't clear enough, I need to fix them.

**Comment by XRaiderXD** [comment]
I'll look into it, thanks!
