### ISSUE TITLE
HELP!

### ISSUE THREAD

**Issue by Vester1E** [Syniurge/ShieldControllerWinDriver#8]
When i do all of that stuff until i can select this there are nothing named "NVIDIA SHIELD CONTROLLER"
![shieldctrldriverstep3](https://cloud.githubusercontent.com/assets/28632013/25963379/5426c4ca-3681-11e7-9edb-9b4acf0be9cd.png)
 BTW do i need to have it in test mode?

**Comment by mirh** [comment]
Check https://github.com/nefarius/ShieldControllerWinDriver/releases/tag/v1.0.0.0

**Comment by Syniurge** [comment]
Hi, sorry my driver doesn't support the 2017 controller model yet, which is why it doesn't show up in the list (different Product ID). I plan to add support soon but I'm currently busy with another project. I'm going to update the README and the Shield tablet forum thread to reflect this.

The 2017 controller however partially works with the generic Windows driver, you just need x360ce for most recent games.

**Comment by Vester1E** [comment]
I made it kinda work, the only thing that works is the trackpad!

**Comment by Syniurge** [comment]
So just to be sure: is your controller the 2017 model? (i.e left on the pic)

![nvidia-shield-2017-android-tv-ah-66](https://cloud.githubusercontent.com/assets/4272771/26555900/c7dcb204-446d-11e7-9f34-4531c1ebd3c7.jpg)

If yes my driver doesn't support it (yet), but you should be able to get the d-pad/sticks/buttons (except the triggers) working with **x360ce**.

I may implement support for the 2017 controllers this week-end.

**Comment by Syniurge** [comment]
So according to the other issue @Vester1E owns the old controller. Let's switch to #10.
